packages:
  # all packages in subdirs of packages/ and components/
  - "api/**"
  - "utils/**"
  - "packages/**"
  - "components/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
