packages:
  # all packages in subdirs of packages/ and components/
  - "components/**"
  - "packages/**"
  - "until/**"
  - "api/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
